### PR TITLE
[2.0.x] Remove Microsoft.NETCore.App from .Design nuspec

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves https://github.com/aspnet/Scaffolding/issues/645

### CODE REVIEW

**Comment by mikeharder** [comment]
@natemcmaster: Do we ship any other packages which target netcoreapp2.0?  Do we use the same pattern in their csproj?

**Comment by natemcmaster** [comment]
:watch: investigating test failures...

**Comment by natemcmaster** [comment]
@mikeharder this is the only package in 2.0.x that has this issue.

**Comment by natemcmaster** [comment]
The test issue: https://github.com/aspnet/Scaffolding/issues/647. Not relate to this change. Moving forward with this update.

**Comment by prafullbhosale** [comment]
> The test issue: #647. Not relate to this change. Moving forward with this update.

Makes sense, wasn't able to see the failures on my machine.

**Pull request merged**
