### PR TITLE
Scaffolding - Fix account confirmation for social logins 

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/AspNetCore-ManualTests/issues/44

This probably should also go into 3.1

### CODE REVIEW

**Comment by ajcvickers** [comment]
@Pilchie I agree with @HaoK that this should go in 3.1. See https://github.com/aspnet/AspNetCore-ManualTests/issues/44#issuecomment-548718780

**Comment by HaoK** [comment]
Note this fix goes into Scaffolding and not AspNetCore

**Comment by Pilchie** [comment]
Adding @vijayrkn for Scaffolding.

**Comment by vijayrkn** [comment]
Scaffolding repo follows the VS approval process. We would need the 16.4 QB approval to merge changes into release/3.1 (except the changes needed to get successful build based on arcade).

**Comment by HaoK** [comment]
@vijayrkn should I start an email thread for the VS process or can we just ping the QB on this PR?

**Comment by mkArtakMSFT** [comment]
Ping @vijayrkn 

> @vijayrkn should I start an email thread for the VS process or can we just ping the QB on this PR?

**Comment by vijayrkn** [comment]
Sorry i missed this comment. Scaffolding ships OOB, so as long as qb is fine with taking the change we can get this into preview3.

**Pull request merged**
