### PR TITLE
Remove '.' from dnx gen command

### PR DESCRIPTION
**Pull request by hishamco**
Removing current directory symbol '.' from ```dnx gen``` command
/cc @Eilon

### CODE REVIEW

**Comment by Eilon** [comment]
@barrytang @mayurid do you have someone to review and merge?

**Comment by mayurid** [comment]
@PradeepKadubandi : Pradeep can you take a look

**Comment by hishamco** [comment]
@PradeepKadubandi any updates about this PR

**Comment by PradeepKadubandi** [comment]
@hishamco , sorry about the delay, I will merge this in a day or two...

**Comment by hishamco** [comment]
No problem, thanks @PradeepKadubandi

**Pull request merged**
