### PR TITLE
Add [ValidateAntiForgeryToken] for all post methods

### PR DESCRIPTION
**Pull request by prafullbhosale**
cc @phenning @barrytang 
@Eilon and @DamianEdwards  for RC2 approval.

### CODE REVIEW

**Comment by Eilon** [comment]
@rynowak @blowdart for the code review.

This shouldn't need RC2 approval because this is tooling, and tooling is wide open right now.

**Comment by blowdart** [comment]
Oh, there are API Controllers. Those should be removed, as it's very dependent on how you call them

**Comment by phenning** [comment]
Same comment as @blowdart, otherwise looks good.

**Comment by prafullbhosale** [comment]
Removed the token for API controllers. 

cc @vkichline

**Comment by prafullbhosale** [comment]
Spoke to @phenning offline. 
This is ok to merge.

**Pull request merged**
