### PR TITLE
Fix obsolete IHostingEnvironment reference

### PR DESCRIPTION
**Pull request by HaoK**
Cherrypick of https://github.com/aspnet/Scaffolding/pull/1037/files

### CODE REVIEW

**Comment by vijayrkn** [comment]
Merging since VS is still in feature development phase & this is primarily used only by VS.

**Comment by vijayrkn** [comment]
@HaoK - can you please port the change to release/3.0 as well so that the change makes it to preview9.

**Comment by HaoK** [comment]
PR for release/3.0 is here https://github.com/aspnet/Scaffolding/pull/1043

**Comment by foconnor-DS** [comment]
Do you all plan to build this as a Preview8 nuget? Or does this change have to wait for Preview9?

Last nuget for codegen/scaffolding is still Preview7:
https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/3.0.0-preview7-19378-04

**Comment by vijayrkn** [comment]
@foconnor-DS - We will be releasing a scaffolding preview8 package soon.

**Comment by foconnor-DS** [comment]
I think you guys made a boo boo. It's not "IWebHostingEnvironment" it's "IWebHostEnvironment". I just pulled down your changes and still get the bug.

If I updated the _Layout.cshtml to be:
```
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
```
Then it works. 

So it's IWebHostEnvironment nor IWebHostingEnvironment.

**Comment by vijayrkn** [comment]
@HaoK?

**Comment by vijayrkn** [comment]
@foconnor-DS - Thank you catching this. 

This is the PR where this change was made - https://github.com/aspnet/AspNetCore/commit/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0

@HaoK - Do you want to update the Scaffolding templates?

**Comment by HaoK** [comment]
Ugh yeah I will submit a new PR

**Comment by HaoK** [comment]
https://github.com/aspnet/Scaffolding/pull/1049

**Pull request merged**
