### PR TITLE
Fix obsolete IHostingEnvironment reference

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/AspNetCore/issues/12676#event-2517102498

### CODE REVIEW

**Comment by HaoK** [comment]
@ajcvickers @vijayrkn is this something that's ok to merge?  Not sure what the criteria is for scaffolding today

**Comment by ajcvickers** [comment]
@HaoK I defer to @vijayrkn on merging.

**Comment by vijayrkn** [comment]
I am planning to re-brand master to 5.0 (just like the rest of the stack) and create a preview8 branch off release/3.0. 

If this is needed in preview9, then this change will have to be cherry-picked to release/3.0 branch after merge.

**Comment by HaoK** [comment]
I think we should take this for 3.0 since without this fix scaffolding results in a compile error, cc @blowdart @danroth27

**Comment by blowdart** [comment]
This does seem blocking to me

**Comment by vijayrkn** [comment]
Preview8 is in ask-mode & we have a preview8 branch. Can you please cherry-pick this change to release/3.0-preview8 branch. I will go ahead and merge this to master.

**Comment by HaoK** [comment]
Alright once this is merged I will cherry pick to preview 8 and submit a PR for that

**Comment by HaoK** [comment]
Actually I can probably do that now without waiting for you to merge

**Comment by HaoK** [comment]
Preview 8 PR is here: https://github.com/aspnet/Scaffolding/pull/1041

**Pull request merged**
