### PR TITLE
Merge changes for 2.0.3 to release

### PR DESCRIPTION
**Pull request by prafullbhosale**
Fixes issues: 
- #633 PR #667 
- #663 PR #658 

Changes from release/2.0 are already rebased into the pb/placeholder_2.0.x branch. 

These fixes have already been ported to dev.

### CODE REVIEW

**Comment by natemcmaster** [comment]
I didn't review product changes carefully, but I didn't see infrastructure changes, so :shipit: from me.

Once this is merged, can you also update the Scaffolding submodule on the release/2.0 branch in aspnet/Universe? If you're not familiar with git submodules, I've [written some instructions here](https://github.com/aspnet/Universe/blob/dev/docs/Submodules.md#saving-an-update-to-a-submodule).

**Comment by Eilon** [comment]
Unfortunately I don't know this codebase at all so I'm not sure I'll be any good at reviewing the functional changes. But I'm with @natemcmaster that as long as the product changes are good, this is good 😄

**Comment by prafullbhosale** [comment]
The functional changes were already reviewed as part of the PRs mentioned above. 
Going to merge this now and update the submodules in universe.

**Comment by prafullbhosale** [comment]
Don't seem to have write access to Universe. @Eilon could you please provide access?

**Comment by natemcmaster** [comment]
I'll take care of updating the submodule.

**Comment by Eilon** [comment]
@prafullbhosale you should have access now too, in case you need to do it again in the future.

**Pull request merged**
