### PR TITLE
Add Microsoft.DotNet.InternalAbstractions dependency to the tools package

### PR DESCRIPTION
**Pull request by prafullbhosale**
cc @NTaylorMullen, @pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by pranavkm** [comment]
Let's make sure @Eilon understands the background for this change before we check it in.

**Comment by prafullbhosale** [comment]
Yes, @NTaylorMullen and I synced up with @Eilon for this.

**Comment by NTaylorMullen** [comment]
:shipit:

**Pull request merged**
