### PR TITLE
Work around razor bug in layout

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/AspNetCore/issues/14064

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
We want this fix for 3.1. Shouldn't this need to target a 3.1 specific branch?

**Comment by mkArtakMSFT** [comment]
Also, I may be confused by the working here, but I assume this is the proper fix, and not simply a work around, isn't it?

**Comment by vijayrkn** [comment]
For 3.1 - it should be cherry-picked.

**Comment by mkArtakMSFT** [comment]
Based on https://github.com/aspnet/AspNetCore/issues/14064#issuecomment-532420102 it sounds like this is indeed a work around. @NTaylorMullen what is the bug being referred here?

**Comment by HaoK** [comment]
The root bug is https://github.com/aspnet/AspNetCore/issues/10811

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen I prefer we fix the root cause, rather than making this change. Given it's `S` let's just do it now. I'm bringing the root-cause issue to 3.1 now. Any objections?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen I prefer we fix the root cause, rather than making this change. Given it's `S` let's just do it now. I'm bringing the root-cause issue to 3.1 now. Any objections?

It's a super edge case so i'm not convinced it's worth the time. I think it makes more sense just to special case this here given it's already done.

**Comment by mkArtakMSFT** [comment]
Aren't there any other side effects similar to this, caused by the actual root cause?

**Comment by NTaylorMullen** [comment]
> Aren't there any other side effects similar to this, caused by the actual root cause?

Nope

**Comment by mkArtakMSFT** [comment]
Let's move forward with this change then, @HaoK!

**Comment by HaoK** [comment]
What's the 3.1 branch to cherry pick to?  I only see 3.0 and 3.0-preview9 I think

**Comment by vijayrkn** [comment]
https://github.com/aspnet/Scaffolding/tree/release/3.1

Just created one off release/3.0

**Pull request merged**
