### PR TITLE
[WIP] Update package refs to 3.0.0-preview3

### PR DESCRIPTION
**Pull request by seancpeters**
Do not checkin. This is a step towards getting to preview4 packages, but is not shippable as-is.

### CODE REVIEW

**Comment by vijayrkn** [comment]
@seancpeters - The tests are failing. Can you please take a look tomorrow?

**Comment by vijayrkn** [comment]
@AndriySvyryd - These are the packages we are looking for the EF preview 4 packages?


```
  <!-- Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -->
    <MicrosoftAspNetCoreDiagnosticsEntityFrameworkCorePackageVersion>3.0.0-preview3-19153-02</MicrosoftAspNetCoreDiagnosticsEntityFrameworkCorePackageVersion>

    <!-- Microsoft.AspNetCore.Identity.EntityFrameworkCore -->
    <MicrosoftAspNetCoreIdentityEntityFrameworkCorePackageVersion>3.0.0-preview3-19153-02</MicrosoftAspNetCoreIdentityEntityFrameworkCorePackageVersion>

    <!-- Microsoft.AspNetCore.Identity.UI -->
    <MicrosoftAspNetCoreIdentityUIPackageVersion>3.0.0-preview3-19153-02</MicrosoftAspNetCoreIdentityUIPackageVersion>

    <!-- Microsoft.Extensions.Identity.Stores -->
    <MicrosoftExtensionsIdentityStoresPackageVersion>3.0.0-preview3-19153-02</MicrosoftExtensionsIdentityStoresPackageVersion>

     <!-- Microsoft.EntityFrameworkCore.Design -->
    <MicrosoftEntityFrameworkCoreDesignPackageVersion>3.0.0-preview3.19153.1</MicrosoftEntityFrameworkCoreDesignPackageVersion>

    <!-- Microsoft.EntityFrameworkCore -->
    <MicrosoftEntityFrameworkCorePackageVersion>3.0.0-preview3.19153.1</MicrosoftEntityFrameworkCorePackageVersion>

    <!-- Microsoft.EntityFrameworkCore.SqlServer -->
    <MicrosoftEntityFrameworkCoreSqlServerPackageVersion>3.0.0-preview3.19153.1</MicrosoftEntityFrameworkCoreSqlServerPackageVersion>
```


/cc @natemcmaster

**Comment by natemcmaster** [comment]
Latest preview4 build versions:
aspnetcore packages 3.0.0-preview4-19210-17
efcore packages 3.0.0-preview4.19210.5

**Comment by seancpeters** [comment]
@natemcmaster - do you know which version of Microsoft.NETCore.App is coherent with the preview4 package versions you mentioned?

**Comment by natemcmaster** [comment]
3.0.0-preview4-27610-0.

Here's a list of the coherent dependencies in case you need others too, like System.\* packages: https://github.com/aspnet/AspNetCore/blob/8af6e9e49ac409e813ca9a8e4832631468f60ed7/eng/Version.Details.xml for aspnetcore  3.0.0-preview4-19210-17

**Comment by seancpeters** [comment]
Closing in favor of #988

**Pull request closed without merging**
