### PR TITLE
Changes to ActivePage declarations for Identity.

### PR DESCRIPTION
**Pull request by seancpeters**
To maintain parity with: https://github.com/aspnet/Identity/issues/1866 and https://github.com/aspnet/Identity/pull/1838

After scaffolding with these changes, the manage account page has links like this (all of which go to an appropriate page):

manage identity changes - simple

### CODE REVIEW

**Comment by seancpeters** [comment]
@mkArtakMSFT - This is still marked as pending shiproom approval. I believe you had coordinated the approval for the related aspnet/identity changes and were going to deal with shiproom approval for these changes - do you know the status of this in regard to shiproom approval?

**Comment by natemcmaster** [comment]
This has not yet been approved for the 2.1 patch. I think this fell off the list of items we were tracking. Can you re-submit this request to shiproom?

**Comment by mkArtakMSFT** [comment]
## Description
 
Manage account page in Scaffolder has broken links.
Also, the ActivePage is not highlighted.
 
## Customer Impact
 
Customers who will scaffold the ManageAccount page will run into this issue (multiple links in the navigation panel reference to the same page).
 
## Regression from?
 
This was broken in 2.1 (and was introduced like this).
 
## Risk
Low

**Comment by mkArtakMSFT** [comment]
@seancpeters looks like the CI build is failing. Please make sure it's fixed.

**Comment by seancpeters** [comment]
@mkArtakMSFT - The CI build failure is due to a timeout, it's sometimes a bit flaky. For now, we can just rerun the CI build (I've just restarted it).

**Comment by vivmishra** [comment]
We can take this in next minor version.

**Comment by seancpeters** [comment]
@mkArtakMSFT - I'm closing this PR as unmerged. With the changes to allow bootstrap version support, this needed to be reworked - it couldn't merge correctly due to file location changes, etc.

So I've made the analogous changes here: https://github.com/aspnet/Scaffolding/pull/862/commits/0a2dd04ea13c5c575caab9082039b4defc9627f6
...which is part of this bootstrap support PR #862

**Pull request closed without merging**
