### PR TITLE
Sync identity UI with scaffolding

### PR DESCRIPTION
**Pull request by HaoK**
Attempt to align scaffolding with current identity UI

Is there any automated coverage that I didn't make any obvious compilation mistakes?

@vijayrkn @seancpeters @javiercn @ajcvickers @blowdart

### CODE REVIEW

**Comment by vijayrkn** [comment]
@HaoK - The PR builds should work. We have enabled them.

**Comment by vijayrkn** [comment]
>that I didn't make any obvious compilation mistakes.
I would assume you have already locally tested these changes as well right?

**Comment by seancpeters** [comment]
The test named TestIdentityGenerator_IndividualFiles_AllFilesBuild()
in this file: https://github.com/aspnet/Scaffolding/blob/master/test/E2E_Test/IdentityScaffolderTests.cs
might be what you're looking for. Unfortunately, it's currently disabled until we can get it working with 3.0

**Comment by HaoK** [comment]
How do I test scaffolding locally?

**Comment by HaoK** [comment]
Or do you just mean run build.cmd?

**Comment by vijayrkn** [comment]
Once you run build.cmd it should generate the CodeGeneration.Design package. You can add/update reference to this package in the local project and try the identity scaffolding scenario. 

It should generate the updated contents and you can validate.

**Comment by seancpeters** [comment]
To test locally, you'll need to get a local build, and then add a package ref to the build result, in a project being scaffolded for testing.

If you run (for example):
`build /t:package /p:_BuildNumberSuffix=t001` 
This will create scaffolding packages under `artifacts\build` 
There should be a file named something like:
`Microsoft.VisualStudio.Web.CodeGeneration.Design.3.0.0-preview4-t001.nupkg`
The `3.0.0-preview4` part will vary based on which branch you're building.
The `t001` part is what was specified on the command line. You should increment the number on each build, to avoid conflicts. The number can be reset if you clear your nuget caches.

Create a new test project, and add a package reference to it for the codegeneration design package, something like this:
`<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0-preview4-t001" PrivateAssets="All" />`

You'll also need to add a nuget source to your test project based on the path to your repo. For example, for me it's: `C:\Github\Scaffolding\artifacts\build`
...because my repo root is `C:\Github\Scaffolding\`

**Comment by HaoK** [comment]
Awesome I'm able to try the scaffolding changes locally and it looks like its mostly working, the first issue I'm seeing now is that the dialog doesn't let me scaffold out some new pages we added, is this something that manually needs to be updated to be able to pickup some new pages?

**Comment by seancpeters** [comment]
With the way things currently work, we'll need to make changes in VS to get those new pages to show up.

**Comment by HaoK** [comment]
Okay, fyi @ajcvickers @blowdart looks like we'll need to coordinate some changes with VS to get the new pages we are adding included in the scaffolding, I'll just copy over the new files for now as a workaround

**Comment by seancpeters** [comment]
@HaoK - I have implemented the functionality for VS and aspnet/Scaffolding to communicate the list of files for identity scaffolding. This #999 is the aspnet/Scaffolding side of the work.

To cause your new files to be available for scaffolding, entries for each of them needs to be added in these files:
https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Identity/bootstrap3_identitygeneratorfilesconfig.json
https://github.com/aspnet/Scaffolding/blob/master/src/VS.Web.CG.Mvc/Identity/bootstrap4_identitygeneratorfilesconfig.json

The format of the entries need to be like the existing entries, as explained here:

Each key is a display name that the entry refers to. Dots are replaced with backslashes
The entries under the display name key represents the list of files that need to be scaffolded when the page is selected. For some entries, this will just be the .cshtml & .cs files corresponding to the key name, but for some, additional "support" files are needed. This example demonstrates a configuration that needs additional files - in addition to the Account.ExternalLogin pages, the Account.Manage._ManageNav and Account.Manage.ManageNavPages files are also listed, and will be scaffolded when Account.ExternalLogin is scaffolded.

Name can be anything, as long as it's unique and consistent per file. By convention, the value of name should be similar to the name of the source file. The name is used for logging, and in some instances in code for when more complex file interactions / requirements are needed.
SourcePath is relative to the Bootstrap3 or Bootstrap4 directory, as appropriate.
OutputPath is relative to the project root, for the project being scaffolded.
IsTemplate indicates whether the file needs to undergo razor processing, or is a static file and can be copied verbatim. 
```
"Account.ExternalLogin": [  
      {
        "Name": "Account.ExternalLogin",
        "SourcePath": "Pages/Account/Account.ExternalLogin.cshtml",
        "OutputPath": "Areas/Identity/Pages/Account/ExternalLogin.cshtml",
        "IsTemplate": false
      },
      {
        "Name": "Account.ExternalLogin.cs",
        "SourcePath": "Account.ExternalLogin.cs.cshtml",
        "OutputPath": "Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs",
        "IsTemplate": true
      },
      {
        "Name": "Account.Manage._ManageNav",
        "SourcePath": "Account.Manage._ManageNav.cshtml",
        "OutputPath": "Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml",
        "IsTemplate": true
      },
      {
        "Name": "Account.Manage.ManageNavPages",
        "SourcePath": "Account.Manage.ManageNavPages.cshtml",
        "OutputPath": "Areas/Identity/Pages/Account/Manage/ManageNavPages.cs",
        "IsTemplate": true
      }
    ],
```

**Comment by HaoK** [comment]
@seancpeters awesome, I will give it a shot soon!

**Comment by HaoK** [comment]
@seancpeters what version of VS do I need to install to pick up your corresponding changes to try things out locally?

**Comment by seancpeters** [comment]
@HaoK - the corresponding VS changes are not yet checked in. When they are available in a VS build I can let you know.

**Comment by HaoK** [comment]
Okay so I'll just prep the changes as best as I can for now, and will wait for a build to test it out

**Comment by HaoK** [comment]
@seancpeters any ETA on bits so we can verify things are working end to end?  Do you think we'll be able to take this for  preview 7?  cc @ajcvickers

**Comment by seancpeters** [comment]
The VS bits for this should be in a build tomorrow.

**Comment by HaoK** [comment]
Awesome @seancpeters looks like things are really close, I was able to verify the new files are showing up in the scaffolder now!

There's only one compilation error which I can't seem to figure out, its from the ViewImports which is generating:

```
@using Microsoft.AspNetCore.Identity
@using ScaffoldTest3.Areas.Identity
@using ScaffoldTest3.Areas.Identity.Data

ScaffoldTest3.Areas.Identity.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

```

Notice how there's a "using" missing from ScaffoldTest3.Areas.Identity.Pages. 

Here's the template code:
```
@inherits Microsoft.VisualStudio.Web.CodeGeneration.Templating.RazorTemplateBase
@@using Microsoft.AspNetCore.Identity
@@using @(Model.Namespace).Areas.Identity
@{
    if (!string.IsNullOrEmpty(Model.UserClassNamespace))
    {
@:@@using @(Model.UserClassNamespace)
    }

}
@@using @(Model.Namespace).Areas.Identity.Pages
@@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
```

**Comment by seancpeters** [comment]
The problem you're seeing with the using is due to this bug:
https://github.com/aspnet/AspNetCore/issues/10811

**Comment by HaoK** [comment]
Thanks @seancpeters I worked around that issue for now just by moving the using higher, and now things run yay...  I'll do some more testing to make sure things work, other than that is there anything else you would like me to do or is this ready to merge?

**Comment by seancpeters** [comment]
I think we're good to go :)

**Comment by vijayrkn** [comment]
Can you please make sure this is ported to the 3.0 branch after merging to master?

**Comment by HaoK** [comment]
@seancpeters looks like the CI failed on linux in a different GC, is this safe to ignore?

**Comment by seancpeters** [comment]
@HaoK - the Linux & mac builds are often flaky. I'm re-running them now.

**Comment by HaoK** [comment]
Awesome thanks!  Are you going to take care of merging this to 3.0 @seancpeters? let me know if you want me to open a PR

**Comment by seancpeters** [comment]
I'll take care of the 3.0 merging. Thanks for bearing with us on getting the communication setup between VS & scaffolding!

**Pull request merged**
